### ISSUE TITLE
Your device doesnt support Multiple advertising

### ISSUE THREAD

**Issue by prachu92** [Thecave3/drone-ble-mesh#17]
![android](https://user-images.githubusercontent.com/55044545/97092747-527f9680-15fb-11eb-936c-a344aed29795.PNG)
I used this code in my android studio. The emulators I used were Nexus 6, Nexus 9, Pixel and Pixel XL.
All the devices show that they do not support multiple advertising. 
How to connect to a server. Could you provide detailed instructions on how to run this.
Thank you

**Comment by Thecave3** [comment]
Hello, 

this project was tested and deployed in a real environment. 
Since it uses BLE, it cannot be run over a simulator.
As it was specified on the readme you must use real smartphones with multiple advertisement.

Cheers

**Comment by prachu92** [comment]
Thanks for the reply. I installed it in two devices. I started the service in two phones.
Now I see "service started" print in both the phones. Nothing much happens after that. Is there a way to start server and client?
![WhatsApp Image 2020-10-30 at 1 57 17 PM](https://user-images.githubusercontent.com/55044545/97756317-ec41ba80-1ab7-11eb-9e28-356f32ff4f2f.jpeg)
