### ISSUE TITLE
Application stuck after the start of the service

### ISSUE THREAD

**Issue by prachu92** [Thecave3/drone-ble-mesh#18]
I installed it in two devices. 
I started the service in two phones.
Now I see "service started" print in both the phones.
Nothing much happens after that. 
Is there a way to start server and client?

<img src="https://user-images.githubusercontent.com/55044545/97756317-ec41ba80-1ab7-11eb-9e28-356f32ff4f2f.jpeg" width="200" height="400" />

**Comment by Thecave3** [comment]
Hi, can you please check the logs of both the smartphones and give us more information? Thank you

**Comment by Thecave3** [comment]
Without further info, it can't be debugged this behaviour

**Comment by prachu92** [comment]
02/06 12:34:34: Launching 'app' on Physical Device.
Install successfully finished in 812 ms.
$ adb shell am start -n "it.drone.mesh/it.drone.mesh.init.InitActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Install successfully finished in 610 ms.
$ adb shell am start -n "it.drone.mesh/it.drone.mesh.init.InitActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 17751 on device 'google-pixel_3-94QX1ZMSF'.
Connected to process 17909 on device 'google-pixel_3_xl-89RY0ABCG'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
[google-pixel_3-94QX1ZMSF]: D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
[google-pixel_3-94QX1ZMSF]: D/NetworkSecurityConfig: No Network Security Config specified, using platform default
[google-pixel_3-94QX1ZMSF]: D/NetworkSecurityConfig: No Network Security Config specified, using platform default
[google-pixel_3-94QX1ZMSF]: I/AppGlobal: Application Started
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
[google-pixel_3_xl-89RY0ABCG]: D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
[google-pixel_3_xl-89RY0ABCG]: D/NetworkSecurityConfig: No Network Security Config specified, using platform default
    No Network Security Config specified, using platform default
[google-pixel_3_xl-89RY0ABCG]: I/AppGlobal: Application Started
[google-pixel_3-94QX1ZMSF]: D/InitActivity: OUD: Everything is supported and enabled
[google-pixel_3_xl-89RY0ABCG]: D/InitActivity: OUD: Everything is supported and enabled
[google-pixel_3-94QX1ZMSF]: I/AdrenoGLES-0: QUALCOMM build                   : ef9bae8, Ia11ce2d146
    Build Date                       : 09/02/20
    OpenGL ES Shader Compiler Version: EV031.31.04.00
    Local Branch                     : gfx-adreno.lnx.2.0
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : C P 11.0.1 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
[google-pixel_3-94QX1ZMSF]: I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
[google-pixel_3-94QX1ZMSF]: W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
    <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
[google-pixel_3-94QX1ZMSF]: I/Gralloc4: mapper 4.x is not supported
[google-pixel_3-94QX1ZMSF]: W/Gralloc3: mapper 3.x is not supported
[google-pixel_3-94QX1ZMSF]: E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
[google-pixel_3_xl-89RY0ABCG]: I/AdrenoGLES-0: QUALCOMM build                   : ef9bae8, Ia11ce2d146
    Build Date                       : 09/02/20
    OpenGL ES Shader Compiler Version: EV031.31.04.00
    Local Branch                     : gfx-adreno.lnx.2.0
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : C P 11.0.1 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
[google-pixel_3_xl-89RY0ABCG]: I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
[google-pixel_3_xl-89RY0ABCG]: W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
    <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
[google-pixel_3_xl-89RY0ABCG]: I/Gralloc4: mapper 4.x is not supported
[google-pixel_3_xl-89RY0ABCG]: W/Gralloc3: mapper 3.x is not supported
[google-pixel_3_xl-89RY0ABCG]: E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
[google-pixel_3_xl-89RY0ABCG]: D/InitActivity: OUD: Service started
[google-pixel_3_xl-89RY0ABCG]: I/TetheringManager: registerTetheringEventCallback:it.drone.mesh
[google-pixel_3_xl-89RY0ABCG]: D/InitActivity: OUD: Ho internet
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: startClient: Scan the background, search servers to join
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=13 mScannerId=0
[google-pixel_3-94QX1ZMSF]: D/InitActivity: OUD: Service started
[google-pixel_3-94QX1ZMSF]: I/TetheringManager: registerTetheringEventCallback:it.drone.mesh
[google-pixel_3-94QX1ZMSF]: D/InitActivity: OUD: Ho internet
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: startClient: Scan the background, search servers to join
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=13 mScannerId=0
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=13 mScannerId=0
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=13 mScannerId=0
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=13 mScannerId=0
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3-94QX1ZMSF]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BLEClient: OUD: Unable to find server available
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothAdapter: isLeEnabled(): ON
[google-pixel_3_xl-89RY0ABCG]: D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=13 mScannerId=0
[google-pixel_3-94QX1ZMSF]: D/BLEClient: OUD: Stopping Scanning
[google-pixel_3-94QX1ZMSF]: D/BluetoothAdapter: isLeEnabled(): ON

**Comment by prachu92** [comment]
@Thecave3 These are the logs from the android studio. I ran on two physical devices(google pixel).
